config/routes.rb
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # Defines the root path route ("/")
  # root "posts#index"

Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  # resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: :category_list_inclusion }
  # attribute :category, Array

  private

  def category_list_inclusion
    ['chinese', 'italian', 'japanese', 'french', 'belgian']
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, :inclusion => { :in => 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    # No need for app/views/restaurants/update.html.erb
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to restaurants_path()
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :phone_number, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
    # No need for app/views/reviews/create.html.erb
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name%>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :category %>
  <%= f.text_field :category%>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number%>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name , restaurant_path(restaurant) %> |
    <%= restaurant.address %> |
    <%= restaurant.category %> |
    <%= restaurant.phone_number %>|
    <%= link_to "Review", new_restaurant_review_path(restaurant) %>
    <%= link_to "Delete", restaurant_path(restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</li>
  <% end %>
  <%= link_to "Create new restaurant" , new_restaurant_path() %>
</ul>


<%# <%= link_to "Delete", restaurant_path(restaurant), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>

app/views/restaurants/new.html.erb
<%= form_with model: @restaurant do |f| %>
  <%= f.label :name%>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :category %>
  <%= f.text_field :category%>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number%>
  <%= f.submit %>
<% end %>

app/views/restaurants/new_review.html.erb
<%= form_with model: @review do |f| %>
  <%= f.label :rating%>
  <%= f.text_field :rating %>
  <%= f.label :content %>
  <%= f.text_field :content %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category%></p>
<p><%= @restaurant.phone_number%></p>

<h2>All reviews</h1>
<ul>
  <% @reviews.each do |review| %>
    <li>|<%= review.rating %> | <%= review.content %>
    </li>
  <% end %>


<%= link_to "Add a new review", new_restaurant_review_path(@restaurant) %>
<%= link_to "Back to list" , restaurants_path() %>
<%= link_to "Edit this post" , edit_restaurant_path() %>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.label :rating%>
  <%= f.text_field :rating %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.submit :save %>
<% end %>